### ISSUE TITLE
Bug || Not Turning Off Audio From Video When Go Off

### ISSUE THREAD

**Issue by fadligenta** [maddog05/whatanime-android#1]
#### Expected behavior<br>
<br>
Hope to mute after selecting video and do not have to turn off the phone to shut down the audio from the video.<br>
<br>
#### Actual behavior<br>
After I chose video suddenly applications out own and could not shut down the audio from the video. to shut down the audio that I have to turn off the phone me and turn it back. please help<br>
<br>
<br>
#### How to reproduce<br>
<br>
* Download the What anime app on playstore Or [Here](https://play.google.com/store/apps/details?id=com.maddog05.whatanime
)
* Launch App<br>
* Skip the app tutorial<br>
* Click on the Video to search for videos<br>
* After finding Click video on video<br>
* Then click on the Checkers icon and the outbound app itself can no longer turn off the video sound<br>
<br>
- Device used: Samsung Grand prime SM-G530<br>
<br>
* Operating System: Android version 4.4.4<br>
<br>
* Application version:1.2.3

#### Recording Of The Bug
https://youtu.be/JdEusQYCDQs

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@fadligenta/bug-or-or-not-turning-off-audio-from-video-when-go-off">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by maddog05** [comment]
@fadligenta The app has been updated to version 1.2.4
I fixed this error with the last commit (and other issues too). The Play Store version need some hours to be updated and can be downloaded to all users.

PD: The video function is still experimental, sometimes works well or not. I need to find other video library but Open Source community can fix this function and send a pull request.
Regards
