### ISSUE TITLE
Language barrier

### ISSUE THREAD

**Issue by Deepblue38** [maddog05/whatanime-android#9]
Hi sorry to bother you but is there an option to change the language from Japanese to English if not then could you add one but if there is could you tell me where to change to thanks

**Comment by maddog05** [comment]
Hi

If you don´t know knowledge about Android, you can download this file (https://github.com/maddog05/whatanime-android/blob/master/app/src/main/res/values/strings.xml) and translate the text inside ( >TEXT< ) to the language that you want to add. Finally, you can send me this modified file here and I will check if it's ok to add the new language to the project. Be careful with Google Translate or help you with other person who know english

Regards
